-- (CREATE DATABASE)COMANDO CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE SPENTENERGY;

-- (USE)COMANDO PARA SELECIONAR O BANCO DE DADOS QUE SERA USADO 
USE SPENTENERGY; 

-- CRIADO TABELA NO BANCO DE DADOS:
-- CREATE TABLE NOME_TABELA (
-- 		NOME_COLUNA TYPE [NOT NULL][PRIMAEY KEY][AUTO_INCREMENT]
-- ) 

CREATE TABLE DEVICE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NR_DEV VARCHAR(30),
    NAME_DEV VARCHAR(50)
);

CREATE TABLE SPENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEV INT NOT NULL,
    TENSION FLOAT,
    POTENCY FLOAT,
    CALC FLOAT,
    VALUE_MED FLOAT,
    HOUR_REG DATETIME,
    FOREIGN KEY (ID_DEV) REFERENCES DEVICE(ID)
);

-- LISTAR TABELA CRIADA
SELECT * FROM DEVICE;

SELECT * FROM SPENT;

-- INSERIR DADOS NA TABELA CRIADA

-- DEVICES 
INSERT INTO DEVICE(NR_DEV, NAME_DEV)
	VALUES('231554','DISPOSITIVO 1');
INSERT INTO DEVICE(NR_DEV, NAME_DEV)
	VALUES('565665','DISPOSITIVO 2');
INSERT INTO DEVICE(NR_DEV, NAME_DEV)
	VALUES('565452','DISPOSITIVO 3');

-- SPENT
INSERT INTO SPENT(ID_DEV,TENSION,POTENCY,CALC,VALUE_MED,HOUR_REG)
	VALUE(1, 12.56, 45.78, 155.45, 12.45, '2019-06-10');
INSERT INTO SPENT(ID_DEV,TENSION,POTENCY,CALC,VALUE_MED,HOUR_REG)
	VALUE(2, 18.56, 12.78, 45.45, 2.45, '2018-12-05 00:39:16');
INSERT INTO SPENT(ID_DEV,TENSION,POTENCY,CALC,VALUE_MED,HOUR_REG)
	VALUE(3, 65.56, 56.78, 56.45, 100, '2019-06-10');
INSERT INTO SPENT(ID_DEV,TENSION,POTENCY,CALC,VALUE_MED,HOUR_REG)
	VALUE(1, 65.56, 100, 100, 52, '2019-02-05 01:00:00');

-- ALTERAR OS DADOS DA TABELA 
UPDATE SPENT SET TENSION = 12.23 WHERE ID = 2 ; 

-- DELETAR INFORMAÇÕES DA TABELA 
DELETE FROM SPENT WHERE ID = 1;

SELECT * FROM SPENT;

-- EXCLUIR TABELA     
DROP TABLE SPENT;   




-- VERIFICAR GRAFICOS

SELECT ID_DEV, SUM(CALC) FROM SPENT
GROUP BY ID_DEV;


select sum(potency),month(hour_reg) from spent
group by month(hour_reg)
ORDER BY ;


SELECT ID_DEV, DAY(HOUR_REG), SUM(VALUE_MED) FROM SPENT
GROUP BY DAY(HOUR_REG), ID_DEV
ORDER BY DAY(HOUR_REG)

SELECT * FROM SPENT
WHERE MONTH(HOUR_REG) = 2 AND  DAY(HOUR_REG) = 2



SELECT MONTH(HOUR_REG), SUM(VALUE_MED) FROM SPENT
GROUP BY MONTH(HOUR_REG)


SELECT MONTH(HOUR_REG) , AVG(calc) FROM SPENT
WHERE ID_DEV = 1
GROUP BY MONTH(HOUR_REG) 


SELECT MONTH(HOUR_REG), AVG(CALC) FROM SPENT
WHERE YEAR(HOUR_REG) = 2019 AND ID_DEV = 1
GROUP BY MONTH(HOUR_REG)